### PR TITLE
Feature/setup

### PR DESCRIPTION
**Pull request by ey-**

### CODE REVIEW

**Comment by ffw-bot-de** [comment]
Build comment file: 
--------------
===============
<strong>4</strong>  errors for CodeSniffer: Drupal standard file http://build15.d8cibox.ffwdeutschland.de/build_reports/Drupalsniff.txt
Build site installed at http://build15.d8cibox.ffwdeutschland.de
Behat tests: standard file http://drupal.192.168.56.132.xip.io/build_reports/report.html
<strong>0</strong> fails for Simpletest: simpletest standard file http://drupal.192.168.56.132.xip.io/build_reports/SimpletestReport.txt

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://d8cibox.ffwdeutschland.de/jenkinsjob/PR_BUILDER/15/

**Comment by ey-** [comment]
retest this please

**Comment by ffw-bot-de** [comment]
Build comment file: 
--------------
===============
<strong>4</strong>  errors for CodeSniffer: Drupal standard file http://build16.d8cibox.ffwdeutschland.de/build_reports/Drupalsniff.txt
Build site installed at http://build16.d8cibox.ffwdeutschland.de
Behat tests: standard file http://drupal.192.168.56.132.xip.io/build_reports/report.html
<strong>0</strong> fails for Simpletest: simpletest standard file http://drupal.192.168.56.132.xip.io/build_reports/SimpletestReport.txt

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://d8cibox.ffwdeutschland.de/jenkinsjob/PR_BUILDER/16/

**Comment by ey-** [comment]
retest this please

**Comment by ffw-bot-de** [comment]
Build comment file: 
--------------
===============
<strong>4</strong>  errors for CodeSniffer: Drupal standard file http://build17.d8cibox.ffwdeutschland.de/build_reports/Drupalsniff.txt
Build site installed at http://build17.d8cibox.ffwdeutschland.de

--------------
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://d8cibox.ffwdeutschland.de/jenkinsjob/PR_BUILDER/17/

**Build Log**
*last 25 lines*

 ```
[...truncated 463 lines...]
fatal: [localhost] => {'msg': "AnsibleUndefinedVariable: One or more undefined variables: 'behat_drupal_root' is undefined", 'failed': True}

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/var/lib/jenkins/tests.retry

localhost                  : ok=1    changed=1    unreachable=1    failed=0   

FATAL: command execution failed
hudson.AbortException: Ansible playbook execution failed
	at org.jenkinsci.plugins.ansible.AnsiblePlaybookBuilder.perform(AnsiblePlaybookBuilder.java:227)
	at org.jenkinsci.plugins.ansible.AnsiblePlaybookBuilder.perform(AnsiblePlaybookBuilder.java:200)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:75)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
	at hudson.model.Build$BuildExecution.build(Build.java:205)
	at hudson.model.Build$BuildExecution.doRun(Build.java:162)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:537)
	at hudson.model.Run.execute(Run.java:1741)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:381)
ERROR: Ansible playbook execution failed
```

**Comment by ffw-bot-de** [comment]
Build comment file: 
--------------
===============
<strong>4</strong>  errors for CodeSniffer: Drupal standard file http://build18.d8cibox.ffwdeutschland.de/build_reports/Drupalsniff.txt
Build site installed at http://build18.d8cibox.ffwdeutschland.de
Behat tests: standard file http://build18.d8cibox.ffwdeutschland.de//build_reports/report.html
<strong>0</strong> fails for Simpletest: simpletest standard file http://build18.d8cibox.ffwdeutschland.de//build_reports/SimpletestReport.txt

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://d8cibox.ffwdeutschland.de/jenkinsjob/PR_BUILDER/18/

**Comment by ey-** [comment]
retest this please

**Comment by ffw-bot-de** [comment]
Build comment file: 
--------------
===============
<strong>4</strong>  errors for CodeSniffer: Drupal standard file http://build19.d8cibox.ffwdeutschland.de/build_reports/Drupalsniff.txt
Build site installed at http://build19.d8cibox.ffwdeutschland.de
Behat tests: standard file http://build19.d8cibox.ffwdeutschland.de//build_reports/report.html
<strong>0</strong> fails for Simpletest: simpletest standard file http://build19.d8cibox.ffwdeutschland.de//build_reports/SimpletestReport.txt

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://d8cibox.ffwdeutschland.de/jenkinsjob/PR_BUILDER/19/

**Comment by ffw-bot-de** [comment]
Build comment file: 
--------------
===============
<strong>4</strong>  errors for CodeSniffer: Drupal standard file http://build20.d8cibox.ffwdeutschland.de/build_reports/Drupalsniff.txt
Build site installed at http://build20.d8cibox.ffwdeutschland.de
Behat tests: standard file http://build20.d8cibox.ffwdeutschland.de//build_reports/report.html
<strong>0</strong> fails for Simpletest: simpletest standard file http://build20.d8cibox.ffwdeutschland.de//build_reports/SimpletestReport.txt

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://d8cibox.ffwdeutschland.de/jenkinsjob/PR_BUILDER/20/

**Comment by ffw-bot-de** [comment]
Build comment file: 
--------------
===============
<strong>4</strong>  errors for CodeSniffer: Drupal standard file http://build21.d8cibox.ffwdeutschland.de/build_reports/Drupalsniff.txt
Build site installed at http://build21.d8cibox.ffwdeutschland.de

--------------
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://d8cibox.ffwdeutschland.de/jenkinsjob/PR_BUILDER/21/

**Build Log**
*last 25 lines*

 ```
[...truncated 470 lines...]


FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/var/lib/jenkins/tests.retry

localhost                  : ok=3    changed=3    unreachable=0    failed=1   

FATAL: command execution failed
hudson.AbortException: Ansible playbook execution failed
	at org.jenkinsci.plugins.ansible.AnsiblePlaybookBuilder.perform(AnsiblePlaybookBuilder.java:227)
	at org.jenkinsci.plugins.ansible.AnsiblePlaybookBuilder.perform(AnsiblePlaybookBuilder.java:200)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:75)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
	at hudson.model.Build$BuildExecution.build(Build.java:205)
	at hudson.model.Build$BuildExecution.doRun(Build.java:162)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:537)
	at hudson.model.Run.execute(Run.java:1741)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:381)
ERROR: Ansible playbook execution failed
```

**Comment by ffw-bot-de** [comment]
Build comment file: 
--------------
===============
<strong>4</strong>  errors for CodeSniffer: Drupal standard file http://build22.d8cibox.ffwdeutschland.de/build_reports/Drupalsniff.txt
Build site installed at http://build22.d8cibox.ffwdeutschland.de
Behat tests: standard file http://build22.d8cibox.ffwdeutschland.de//build_reports/report.html
<strong>0</strong> fails for Simpletest: simpletest standard file http://build22.d8cibox.ffwdeutschland.de//build_reports/SimpletestReport.txt

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://d8cibox.ffwdeutschland.de/jenkinsjob/PR_BUILDER/22/

**Comment by ffw-bot-de** [comment]
Build comment file: 
--------------
===============
<strong>4</strong>  errors for CodeSniffer: Drupal standard file http://build23.d8cibox.ffwdeutschland.de/build_reports/Drupalsniff.txt
Build site installed at http://build23.d8cibox.ffwdeutschland.de
Behat tests: standard file http://build23.d8cibox.ffwdeutschland.de//build_reports/report.html
<strong>0</strong> fails for Simpletest: simpletest standard file http://build23.d8cibox.ffwdeutschland.de//build_reports/SimpletestReport.txt

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://d8cibox.ffwdeutschland.de/jenkinsjob/PR_BUILDER/23/

**Comment by ffw-bot-de** [comment]
Build comment file: 
--------------
===============
<strong>4</strong>  errors for CodeSniffer: Drupal standard file http://build24.d8cibox.ffwdeutschland.de/build_reports/Drupalsniff.txt
Build site installed at http://build24.d8cibox.ffwdeutschland.de
Behat tests: standard file http://build24.d8cibox.ffwdeutschland.de//build_reports/report.html
<strong>0</strong> fails for Simpletest: simpletest standard file http://build24.d8cibox.ffwdeutschland.de//build_reports/SimpletestReport.txt

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://d8cibox.ffwdeutschland.de/jenkinsjob/PR_BUILDER/24/

**Comment by ffw-bot-de** [comment]
Build comment file: 
--------------
===============
<strong>4</strong>  errors for CodeSniffer: Drupal standard file http://build25.d8cibox.ffwdeutschland.de/build_reports/Drupalsniff.txt
Build site installed at http://build25.d8cibox.ffwdeutschland.de
Behat tests: standard file http://build25.d8cibox.ffwdeutschland.de//build_reports/report.html
<strong>0</strong> fails for Simpletest: simpletest standard file http://build25.d8cibox.ffwdeutschland.de//build_reports/SimpletestReport.txt

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://d8cibox.ffwdeutschland.de/jenkinsjob/PR_BUILDER/25/

**Pull request merged**
